name = "HtmlTables"
uuid = "904c20a5-5d93-408b-bcdf-4b1270b5a8fe"
authors = ["Piet Van Der Paelt"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
